### ISSUE TITLE
Lambdasync logs UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by appernetic** [fanderzon/lambdasync#16]
I tried lambdasync logs and got more info:
(node:9906) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): NoSuchEntity: Role not found for LambdasyncExecRole
moset:create-seller-account serv1$ lambdasync logs
{ ResourceNotFoundException: The specified log group does not exist.
    at Request.extractError (/Users/serv1/.npm-packages/lib/node_modules/lambdasync/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/Users/serv1/.npm-packages/lib/node_modules/lambdasync/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/serv1/.npm-packages/lib/node_modules/lambdasync/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/serv1/.npm-packages/lib/node_modules/lambdasync/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/serv1/.npm-packages/lib/node_modules/lambdasync/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/serv1/.npm-packages/lib/node_modules/lambdasync/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/serv1/.npm-packages/lib/node_modules/lambdasync/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/serv1/.npm-packages/lib/node_modules/lambdasync/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/serv1/.npm-packages/lib/node_modules/lambdasync/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/Users/serv1/.npm-packages/lib/node_modules/lambdasync/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The specified log group does not exist.',
  code: 'ResourceNotFoundException',
  time: 2017-02-23T07:49:48.910Z,
  requestId: 'a6b7b3a2-f99c-11e6-8e39-4d991c6bb1c4',
  statusCode: 400,
  retryable: false,
  retryDelay: 99.70978368801315 }

**Comment by fanderzon** [comment]
Thanks a lot for reporting this, I can see that 2 things went wrong here.

1) lambdasync failed to create it's `LambdasyncExecRole`, this has been fixed in the newly released 3.1.1 version of lambdasync
2) It tried to read the logs for a function that wasn't yet created on AWS, so that failed too. I've caught this case as well and printed out a hopefully helpful error message about needing to deploy the function before getting logs.

I really hope this is the last of your problems with lambdasync, but if you do run into anything else I do appreciate these reports. 🙂
